### ISSUE TITLE
脚本小概率异常

### ISSUE THREAD

**Issue by fengyangyang98** [linfs-art/CloudComputingTestScripts#5]
脚本运行的过程中小概率会异常退出，这个时候后台还是会运行测试程序，再次运行脚本进行下一次测试的时候会导致一些不可预料的问题。

使用：

`ps -ef | grep kvstore2pcsystem | awk '{print $2}' | xargs kill`

可以解决的这个问题，保证下一次测试的正确。

请问一下助教可以不可以添加 cmake 编译的方式呢。

**Comment by linfs-art** [comment]
看来你已经很容易地看懂脚本了，cmake如果可以你可以自己往脚本里添加，然后再pull request一波，，修改的时候留意一下仓库有没有更新，在最新的脚本上进行修改
